Added sun frustum culling to reduce draw calls for shadow pass. Fixed…
lragnarsson/Emerald-Engine pull request #135
Opened 2016-12-28 14:51 UTC by lragnarsson

… wind noise bias on grass animation.

2016-12-28 17:14 UTC, hansfilipelo requested changes
See note on scene file.

2016-12-28 17:14 UTC, hansfilipelo commented on res/scenes/terrain_demo.txt
> -res/models/tree_dry_1/Tree_Dry_1.obj | rel | 0 184 0 | -22 -3 173 | 0.005 | -1 -1 | -1
Why remove all models from demo?

2016-12-28 17:14 UTC, hansfilipelo commented on src/Renderer.cpp
> +    }
This is great :)

2016-12-28 17:14 UTC, hansfilipelo commented on src/shaders/ssao.frag
> +
This doesn't really add anything performance-wise since both branches are still "executed" - but I agree with the change anyway.

2016-12-28 18:10 UTC, lragnarsson commented on res/scenes/terrain_demo.txt
> -res/models/tree_dry_1/Tree_Dry_1.obj | rel | 0 184 0 | -22 -3 173 | 0.005 | -1 -1 | -1
Most computers seem to run out of VRAM with so many models :/

2016-12-28 18:12 UTC, lragnarsson commented on src/shaders/ssao.frag
> +
It seems to improve my performance quite a bit. When half the screen is sky there is a much lower penalty for having SSAO active on my desktop computer.

2016-12-29 09:46 UTC, hansfilipelo approved these changes

2016-12-29 09:46 UTC, merged