Bloom labs
lragnarsson/Emerald-Engine pull request #70
Opened 2016-09-25 08:40 UTC by lragnarsson

2016-10-02 18:07 UTC, hansfilipelo requested changes

2016-10-02 18:07 UTC, hansfilipelo commented on src/Renderer.cpp
> +        glUniform1i(glGetUniformLocation(shader, "horizontal"), false);
This should be done using two different shaders, one for horizontal and one for vertical. 

As it is right now we get branching in each of them, making calculations for both branches in each. We will improve performance by separating them into two different shaders.

2016-10-02 18:07 UTC, hansfilipelo commented on src/shaders/blur_rgb_11.frag
> +    if (horizontal) {
See earlier comment about this shader.

2016-10-02 18:07 UTC, hansfilipelo commented on src/shaders/blur_rgb_5.frag
> +    if (horizontal) {
Same applies here.

2016-10-02 18:07 UTC, hansfilipelo commented on src/shaders/ssao.frag
>  uniform vec3 samples[256]; // Kernel samples from surrounding screen space geometry
Should probably be: 

```
uniform vec3 samples[_SSAO_N_SAMPLES_]
```

2016-10-25 08:41 UTC, hansfilipelo approved these changes

2016-10-25 08:41 UTC, hansfilipelo commented
Post processing kills performance on my MacBook. Post processing stage averages 35-36 ms.

2016-10-25 08:41 UTC, hansfilipelo commented
Is it possible to disable bloom?

2016-10-25 08:53 UTC, Isakwiberg commented
Post processing averages 55 ms on my MacBook. If I lower the number of blur passes from 3 to 2 in Renderer.cpp line 309 I get 0.5 ms average time! Strange.

2016-10-25 09:17 UTC, merged